/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.steamif.telas;

import com.steamif.dao.UsuarioDAO;
import com.steamif.models.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bfeli
 */
public class TelaCadastrados extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios = new ArrayList<Usuario>();

    /**
     * Creates new form TelaCadastrados
     */
    public TelaCadastrados() {
        initComponents();
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarios = usuarioDAO.listarUsuarios();

        if (!usuarios.isEmpty()) {
            String[] nomes = new String[usuarios.size()];

            for (int i = 0; i < usuarios.size(); i++) {
                nomes[i] = usuarios.get(i).getNome();
                listaUsuarios.setListData(nomes);
            }
        } else {
            String[] naoNome = new String[1];
            naoNome[0] = "Não há usuários cadastrados!";
            listaUsuarios.setListData(naoNome);
        }
        
        getContentPane().setBackground(new Color(89, 0, 179));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        deletarUsuario = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/steamif/telas/imagens/Logo 100px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        listaUsuarios.setBackground(new java.awt.Color(153, 102, 255));
        listaUsuarios.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        listaUsuarios.setForeground(new java.awt.Color(102, 0, 102));
        jScrollPane1.setViewportView(listaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 340, 170));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("USUARIOS CADASTRADOS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deletarUsuario.setBackground(new java.awt.Color(102, 0, 51));
        deletarUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        deletarUsuario.setForeground(new java.awt.Color(204, 204, 255));
        deletarUsuario.setText("Deletar");
        deletarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(deletarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 90, 30));

        botaoVoltar.setBackground(new java.awt.Color(102, 0, 51));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(204, 204, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 470, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        new TelaAdm().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void deletarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarUsuarioActionPerformed
        // TODO add your handling code here:
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarios = usuarioDAO.listarUsuarios();

        for (int i = 0; i < usuarios.size(); i++) {
            if (listaUsuarios.getSelectedValue().equals(usuarios.get(i).getNome())) {
                if (usuarios.get(i).isAdm() == false) {
                    usuarioDAO.excluirUsuario(usuarios.get(i).getId());
                    JOptionPane.showMessageDialog(null, "Usuário deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Não é possível deletar um adm!");
                    break;
                }
            }
        }
        UsuarioDAO usuarioDAO2 = new UsuarioDAO();
        usuarios = usuarioDAO2.listarUsuarios();

        String[] nomes = new String[usuarios.size()];

        for (int j = 0; j < usuarios.size(); j++) {
            nomes[j] = usuarios.get(j).getNome();
            listaUsuarios.setListData(nomes);
        }

    }//GEN-LAST:event_deletarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton deletarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
