/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.steamif.telas;
import com.steamif.dao.UsuarioDAO;
import com.steamif.models.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author bfeli
 */
public class TelaAdm extends javax.swing.JFrame {
    
    private int id;
    
    /**
     * Creates new form TelaAdm
     */
    public TelaAdm() {
        id = TelaEntrar.getId();
        initComponents();
        getContentPane().setBackground(new Color(89, 0, 179));
        
        //Adiciona as informações do adm
        UsuarioDAO usuariodao = new UsuarioDAO();
        Usuario usuario = usuariodao.consultarPorId(id);
        nomeUsuario.setText(usuario.getNome());
        emailUsuario.setText(usuario.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SteamIF = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        voltarCatalogo = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        emailUsuario = new javax.swing.JTextField();
        nomeUsuario = new javax.swing.JTextField();
        biblioteca = new javax.swing.JButton();
        deletarConta = new javax.swing.JButton();
        verUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/steamif/telas/imagens/icon people.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        SteamIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/steamif/telas/imagens/Logo 100px.png"))); // NOI18N
        getContentPane().add(SteamIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 153));
        jLabel9.setText("Nome:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 43));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 43, 254, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 153));
        jLabel10.setText("Email:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        sair.setBackground(new java.awt.Color(255, 153, 153));
        sair.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        sair.setForeground(new java.awt.Color(102, 0, 51));
        sair.setText("SAIR DA CONTA");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel1.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Administrador");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        voltarCatalogo.setBackground(new java.awt.Color(102, 153, 255));
        voltarCatalogo.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        voltarCatalogo.setForeground(new java.awt.Color(204, 255, 255));
        voltarCatalogo.setText("VOLTAR AO CATÁLOGO");
        voltarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCatalogoActionPerformed(evt);
            }
        });
        jPanel1.add(voltarCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 200, -1));

        atualizar.setBackground(new java.awt.Color(255, 153, 153));
        atualizar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        atualizar.setForeground(new java.awt.Color(102, 0, 51));
        atualizar.setText("ATUALIZAR DADOS");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        jPanel1.add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, 30));

        emailUsuario.setBackground(new java.awt.Color(204, 153, 255));
        emailUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        emailUsuario.setForeground(new java.awt.Color(102, 0, 102));
        emailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(emailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 380, 30));

        nomeUsuario.setBackground(new java.awt.Color(204, 153, 255));
        nomeUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        nomeUsuario.setForeground(new java.awt.Color(102, 0, 102));
        nomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(nomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 380, 30));

        biblioteca.setBackground(new java.awt.Color(51, 153, 255));
        biblioteca.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        biblioteca.setForeground(new java.awt.Color(204, 255, 255));
        biblioteca.setText("BIBLIOTECA DE JOGOS");
        biblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaActionPerformed(evt);
            }
        });
        jPanel1.add(biblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 200, 30));

        deletarConta.setBackground(new java.awt.Color(255, 153, 153));
        deletarConta.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        deletarConta.setForeground(new java.awt.Color(102, 0, 51));
        deletarConta.setText("DELETAR CONTA");
        deletarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarContaActionPerformed(evt);
            }
        });
        jPanel1.add(deletarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 130, 30));

        verUsuarios.setBackground(new java.awt.Color(255, 153, 153));
        verUsuarios.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        verUsuarios.setForeground(new java.awt.Color(102, 0, 51));
        verUsuarios.setText("VERIFICAR USUARIOS");
        verUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(verUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 600, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sairActionPerformed

    private void voltarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCatalogoActionPerformed
        // TODO add your handling code here:
        new TelaAcessar().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarCatalogoActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        String novoNome = nomeUsuario.getText();
        String novoEmail = emailUsuario.getText();

        UsuarioDAO usuariodao = new UsuarioDAO();
        usuariodao.atualizarUsuario(novoNome, novoEmail, id);

        Usuario usuario = usuariodao.consultarPorId(id);
        nomeUsuario.setText(usuario.getNome());
        emailUsuario.setText(usuario.getEmail());
        
        JOptionPane.showMessageDialog(null , "Dados atualizados!!!");
    }//GEN-LAST:event_atualizarActionPerformed

    private void emailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailUsuarioActionPerformed

    private void nomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioActionPerformed

    private void bibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaActionPerformed
        // TODO add your handling code here:
        new TelaBiblioteca().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bibliotecaActionPerformed

    private void deletarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarContaActionPerformed
        // TODO add your handling code here:
        id = TelaEntrar.getId();
        UsuarioDAO usuariodao = new UsuarioDAO();
        usuariodao.excluirUsuario(id);
        JOptionPane.showMessageDialog(null, "CONTA EXCLUÍDA");
        new TelaLogin().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_deletarContaActionPerformed

    private void verUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verUsuariosActionPerformed
        // TODO add your handling code here:
        new TelaCadastrados().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_verUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SteamIF;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton biblioteca;
    private javax.swing.JButton deletarConta;
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeUsuario;
    private javax.swing.JButton sair;
    private javax.swing.JButton verUsuarios;
    private javax.swing.JButton voltarCatalogo;
    // End of variables declaration//GEN-END:variables
}
